/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAccountForm: typeof import('./features/admins/components/presenters/AdminAccountForm/AdminAccountForm.vue')['default'];
    AdminAccountSettings: typeof import('./features/admins/components/containers/AdminAccountSettings/AdminAccountSettings.vue')['default'];
    AdminAuthenticationSettings: typeof import('./features/admins/components/containers/AdminAuthenticationSettings/AdminAuthenticationSettings.vue')['default'];
    AdminProfileForm: typeof import('./features/admins/components/presenters/AdminProfileForm/AdminProfileForm.vue')['default'];
    AdminProfileSettings: typeof import('./features/admins/components/containers/AdminProfileSettings/AdminProfileSettings.vue')['default'];
    AdminsView: typeof import('./features/admins/views/AdminsView.vue')['default'];
    AdminUsernameForm: typeof import('./features/admins/components/presenters/AdminUsernameForm/AdminUsernameForm.vue')['default'];
    AdminView: typeof import('./features/admins/views/AdminView.vue')['default'];
    AlbumAppearanceSettings: typeof import('./features/albums/components/containers/AlbumAppearanceSettings/AlbumAppearanceSettings.vue')['default'];
    AlbumArtistsForm: typeof import('./features/albums/components/presenters/AlbumArtistsForm/AlbumArtistsForm.vue')['default'];
    AlbumCommonSettings: typeof import('./features/albums/components/containers/AlbumCommonSettings/AlbumCommonSettings.vue')['default'];
    AlbumCoverForm: typeof import('./features/albums/components/presenters/AlbumCoverForm/AlbumCoverForm.vue')['default'];
    AlbumProfileForm: typeof import('./features/albums/components/presenters/AlbumProfileForm/AlbumProfileForm.vue')['default'];
    AlbumProfileSettings: typeof import('./features/albums/components/containers/AlbumProfileSettings/AlbumProfileSettings.vue')['default'];
    AlbumSettingsForm: typeof import('./features/albums/components/presenters/AlbumSettingsForm/AlbumSettingsForm.vue')['default'];
    AlbumsView: typeof import('./features/albums/views/AlbumsView.vue')['default'];
    AlbumTrackDrawer: typeof import('./features/albums/components/containers/AlbumTrackSettingsDrawer/AlbumTrackDrawer.vue')['default'];
    AlbumTracks: typeof import('./features/tracks/components/containers/AlbumTracks/AlbumTracks.vue')['default'];
    AlbumTrackSettingsDrawer: typeof import('./features/albums/components/containers/AlbumTrackSettingsDrawer/AlbumTrackSettingsDrawer.vue')['default'];
    AlbumTracksSettings: typeof import('./features/albums/components/containers/AlbumTracksSettings/AlbumTracksSettings.vue')['default'];
    AlbumView: typeof import('./features/albums/views/AlbumView.vue')['default'];
    App: typeof import('./App.vue')['default'];
    ArtistAlbums: typeof import('./features/albums/components/containers/ArtistAlbums/ArtistAlbums.vue')['default'];
    ArtistAlbumsSettings: typeof import('./features/artists/components/containers/ArtistAlbumsSettings/ArtistAlbumsSettings.vue')['default'];
    ArtistAppearanceSettings: typeof import('./features/artists/components/containers/ArtistAppearanceSettings/ArtistAppearanceSettings.vue')['default'];
    ArtistAvatarForm: typeof import('./features/artists/components/presenters/ArtistAvatarForm/ArtistAvatarForm.vue')['default'];
    ArtistCommonSettings: typeof import('./features/artists/components/containers/ArtistCommonSettings/ArtistCommonSettings.vue')['default'];
    ArtistCoverForm: typeof import('./features/artists/components/presenters/ArtistCoverForm/ArtistCoverForm.vue')['default'];
    ArtistLinks: typeof import('./shared/components/presenters/ArtistLinks/ArtistLinks.vue')['default'];
    ArtistProfileForm: typeof import('./features/artists/components/presenters/ArtistProfileForm/ArtistProfileForm.vue')['default'];
    ArtistProfileSettings: typeof import('./features/artists/components/containers/ArtistProfileSettings/ArtistProfileSettings.vue')['default'];
    ArtistSettingsForm: typeof import('./features/artists/components/presenters/ArtistSettingsForm/ArtistSettingsForm.vue')['default'];
    ArtistsView: typeof import('./features/artists/views/ArtistsView.vue')['default'];
    ArtistView: typeof import('./features/artists/views/ArtistView.vue')['default'];
    CreateButton: typeof import('./shared/components/presenters/CreateButton/CreateButton.vue')['default'];
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default'];
    DeleteButton: typeof import('./shared/components/presenters/DeleteButton/DeleteButton.vue')['default'];
    DeleteConfirmation: typeof import('./shared/components/presenters/DeleteConfirmation/DeleteConfirmation.vue')['default'];
    DeleteConfirmationDialog: typeof import('./shared/components/presenters/DeleteConfirmationDialog/DeleteConfirmationDialog.vue')['default'];
    HomeView: typeof import('./features/home/HomeView.vue')['default'];
    ImageUploader: typeof import('./shared/components/containers/ImageUploader/ImageUploader.vue')['default'];
    LogoHomeLink: typeof import('./shared/components/presenters/LogoHomeLink/LogoHomeLink.vue')['default'];
    NavMenu: typeof import('./shared/components/presenters/NavMenu/NavMenu.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    UIAutocomplete: typeof import('./shared/components/presenters/UI/UIAutocomplete/UIAutocomplete.vue')['default'];
    UIButton: typeof import('./shared/components/presenters/UI/UIButton/UIButton.vue')['default'];
    UICheckbox: typeof import('./shared/components/presenters/UI/UICheckbox/UICheckbox.vue')['default'];
    UIColorPicker: typeof import('./shared/components/presenters/UI/UIColorPicker/UIColorPicker.vue')['default'];
    UIContentSection: typeof import('./shared/components/presenters/UI/UIContentSection/UIContentSection.vue')['default'];
    UIDatePicker: typeof import('./shared/components/presenters/UI/UIDatePicker/UIDatePicker.vue')['default'];
    UIDialog: typeof import('./shared/components/presenters/UI/UIDialog/UIDialog.vue')['default'];
    UIDrawer: typeof import('./shared/components/presenters/UI/UIDrawer/UIDrawer.vue')['default'];
    UIForm: typeof import('./shared/components/presenters/UI/UIForm/UIForm.vue')['default'];
    UIHeading: typeof import('./shared/components/presenters/UI/UIHeading/UIHeading.vue')['default'];
    UIIcon: typeof import('./shared/components/presenters/UI/UIIcon/UIIcon.vue')['default'];
    UIInput: typeof import('./shared/components/presenters/UI/UIInput/UIInput.vue')['default'];
    UILink: typeof import('./shared/components/presenters/UI/UILink/UILink.vue')['default'];
    UINumberInput: typeof import('./shared/components/presenters/UI/UINumberInput/UINumberInput.vue')['default'];
    UIRadioGroup: typeof import('./shared/components/presenters/UI/UIRadioGroup/UIRadioGroup.vue')['default'];
    UISelect: typeof import('./shared/components/presenters/UI/UISelect/UISelect.vue')['default'];
    UISpinner: typeof import('./shared/components/presenters/UI/UISpinner/UISpinner.vue')['default'];
    UIStateIcon: typeof import('./shared/components/presenters/UI/UIStateIcon/UIStateIcon.vue')['default'];
    UISwitch: typeof import('./shared/components/presenters/UI/UISwitch/UISwitch.vue')['default'];
    UITable: typeof import('./shared/components/presenters/UI/UITable/UITable.vue')['default'];
    UITabs: typeof import('./shared/components/presenters/UI/UITabs/UITabs.vue')['default'];
    UIText: typeof import('./shared/components/presenters/UI/UIText/UIText.vue')['default'];
    UITextarea: typeof import('./shared/components/presenters/UI/UITextarea/UITextarea.vue')['default'];
    ViewBody: typeof import('./shared/components/presenters/ViewBody/ViewBody.vue')['default'];
    ViewHeader: typeof import('./shared/components/presenters/ViewHeader/ViewHeader.vue')['default'];
  }
}
