/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminsView: typeof import('./features/admins/AdminsView.vue')['default']
    App: typeof import('./App.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    HomeView: typeof import('./features/home/HomeView.vue')['default']
    LogoHomeLink: typeof import('./shared/components/presenters/LogoHomeLink/LogoHomeLink.vue')['default']
    NavMenu: typeof import('./shared/components/presenters/NavMenu/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UIAutocomplete: typeof import('./shared/components/presenters/UI/UIAutocomplete/UIAutocomplete.vue')['default']
    UIButton: typeof import('./shared/components/presenters/UI/UIButton/UIButton.vue')['default']
    UICheckbox: typeof import('./shared/components/presenters/UI/UICheckbox/UICheckbox.vue')['default']
    UIColorPicker: typeof import('./shared/components/presenters/UI/UIColorPicker/UIColorPicker.vue')['default']
    UIContentSection: typeof import('./shared/components/presenters/UI/UIContentSection/UIContentSection.vue')['default']
    UIDatePicker: typeof import('./shared/components/presenters/UI/UIDatePicker/UIDatePicker.vue')['default']
    UIDialog: typeof import('./shared/components/presenters/UI/UIDialog/UIDialog.vue')['default']
    UIDrawer: typeof import('./shared/components/presenters/UI/UIDrawer/UIDrawer.vue')['default']
    UIForm: typeof import('./shared/components/presenters/UI/UIForm/UIForm.vue')['default']
    UIHeading: typeof import('./shared/components/presenters/UI/UIHeading/UIHeading.vue')['default']
    UIIcon: typeof import('./shared/components/presenters/UI/UIIcon/UIIcon.vue')['default']
    UIInput: typeof import('./shared/components/presenters/UI/UIInput/UIInput.vue')['default']
    UILink: typeof import('./shared/components/presenters/UI/UILink/UILink.vue')['default']
    UINumberInput: typeof import('./shared/components/presenters/UI/UINumberInput/UINumberInput.vue')['default']
    UIRadioGroup: typeof import('./shared/components/presenters/UI/UIRadioGroup/UIRadioGroup.vue')['default']
    UISelect: typeof import('./shared/components/presenters/UI/UISelect/UISelect.vue')['default']
    UISpinner: typeof import('./shared/components/presenters/UI/UISpinner/UISpinner.vue')['default']
    UIStateIcon: typeof import('./shared/components/presenters/UI/UIStateIcon/UIStateIcon.vue')['default']
    UISwitch: typeof import('./shared/components/presenters/UI/UISwitch/UISwitch.vue')['default']
    UITable: typeof import('./shared/components/presenters/UI/UITable/UITable.vue')['default']
    UITabs: typeof import('./shared/components/presenters/UI/UITabs/UITabs.vue')['default']
    UIText: typeof import('./shared/components/presenters/UI/UIText/UIText.vue')['default']
    UITextarea: typeof import('./shared/components/presenters/UI/UITextarea/UITextarea.vue')['default']
  }
}
